### ISSUE TITLE
client.shared.js fails to build - could not find the assigment to "asmLibraryArg"

### ISSUE THREAD

**Issue by k2snowman69** [snowcoders/boilerplate-emscripten-typescript#12]
When I run make
```
D:\Projects\boilerplate-emscripten-typescript\client.shared.js>mingw32-make
```

The output I get is the following:
```
emcc --bind ..\client.shared\ship\client.shared.bc -o ship\client-shared.js -std=c++11 -Oz -s NO_EXIT_RUNTIME=1 --pre-js .\src\prefix.js --post-js .\src\postfix.js
Stack: Error
    at assertTrue (eval at globalEval (D:\Emscripten\emscripten\1.38.12\tools\js-optimizer.js:114:8), <anonymous>:59:26)
    at Object.emitDCEGraph (D:\Emscripten\emscripten\1.38.12\tools\js-optimizer.js:8182:3)
    at D:\Emscripten\emscripten\1.38.12\tools\js-optimizer.js:8406:14
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (D:\Emscripten\emscripten\1.38.12\tools\js-optimizer.js:8405:21)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)

undefined:60
    throw msg;
    ^
Assertion failed: could not find the assigment to "asmLibraryArg". perhaps --pre-js or --post-js code moved it out of the global scope? (things like that should be done after emcc runs, as they do not need to be run through the optimizer which is the special thing about --pre-js/--post-js code)
```

**Comment by k2snowman69** [comment]
In general with the latest emscripten seems a lot has broken. I've gotten it so that the mocha tests run, working on getting typing to work properly.

**Comment by k2snowman69** [comment]
Looks like a few people are talking about generating out the d.ts here
https://github.com/kripken/emscripten/issues/7083

Maybe something we should track
